//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conexion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_CeciliaGabriela_EscalonaChavarriaEntities : DbContext
    {
        public DB_CeciliaGabriela_EscalonaChavarriaEntities()
            : base("name=DB_CeciliaGabriela_EscalonaChavarriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fabricante> fabricantes { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
    
        public virtual int Insertar(string nombre, Nullable<decimal> precio, Nullable<int> codigo_fabricante)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var codigo_fabricanteParameter = codigo_fabricante.HasValue ?
                new ObjectParameter("codigo_fabricante", codigo_fabricante) :
                new ObjectParameter("codigo_fabricante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insertar", nombreParameter, precioParameter, codigo_fabricanteParameter);
        }
    
        public virtual ObjectResult<ListaProducto_Result> ListaProducto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaProducto_Result>("ListaProducto");
        }
    
        public virtual ObjectResult<ListaFabricante_Result> ListaFabricante()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaFabricante_Result>("ListaFabricante");
        }
    }
}
